import type { GalleryItem } from "@/types";

// Gallery items from past editions.
// To add new photos/videos: add entries here and place files in public/images/gallery/
export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: "photo-001",
    type: "photo",
    src: "/images/gallery/imagen-1.jpeg",
    alt: "Delegación de ballet folclórico con trajes rojos bailando en el escenario del Encuentro Latinoamericano",
    caption: "Ballet folclórico en escena — Encuentro Latinoamericano",
    year: 2024,
  },
  {
    id: "photo-002",
    type: "photo",
    src: "/images/gallery/imagen-2.jpeg",
    alt: "Parejas de distintas edades bailando danzas folclóricas con vestimenta tradicional gaucha",
    caption: "Danzas tradicionales gauchas — Encuentro Latinoamericano",
    year: 2024,
  },
  {
    id: "photo-003",
    type: "photo",
    src: "/images/gallery/imagen-3.jpeg",
    alt: "Ballet con vestidos celestes y blancos actuando ante el público con banners del Encuentro Latinoamericano de fondo",
    caption: "Ballet celeste y blanco ante el público — Encuentro Latinoamericano",
    year: 2024,
  },
  {
    id: "photo-004",
    type: "photo",
    src: "/images/gallery/imagen-4.jpeg",
    alt: "Grupo de mujeres con faldas celestes bailando folclore en el escenario del Encuentro",
    caption: "Folclore femenino en escena — Encuentro Latinoamericano",
    year: 2024,
  },
  {
    id: "photo-005",
    type: "photo",
    src: "/images/gallery/imagen-5.jpeg",
    alt: "Grupo de percusionistas tocando bombos legüeros en el escenario del Encuentro Latinoamericano con el público aplaudiendo",
    caption: "Percusión folclórica — bombos legüeros en vivo",
    year: 2024,
  },
  {
    id: "photo-006",
    type: "photo",
    src: "/images/gallery/imagen-6.jpeg",
    alt: "Parejas bailando chacarera con trajes coloridos y faldas floreadas ante el público",
    caption: "Chacarera en pareja — Encuentro Latinoamericano",
    year: 2024,
  },
  {
    id: "photo-007",
    type: "photo",
    src: "/images/gallery/imagen-7.jpeg",
    alt: "Niños bailando danzas folclóricas con vestimenta tradicional en el Encuentro Latinoamericano",
    caption: "Los más pequeños también bailan — Encuentro Latinoamericano",
    year: 2024,
  },
  // Videos - Replace these YouTube URLs with your own event videos
  {
    id: "video-001",
    type: "video",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    caption: "Video destacado del Encuentro Latinoamericano 2024",
    alt: "Video del festival folclórico",
    year: 2024,
  },
  {
    id: "video-002",
    type: "video",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    caption: "Actuación Ballet Folclórico — Edición 2024",
    alt: "Video de ballet folclórico en el escenario",
    year: 2024,
  },
  {
    id: "video-003",
    type: "video",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    caption: "Resumen Encuentro Latinoamericano 2023",
    alt: "Resumen del encuentro 2023",
    year: 2023,
  },
  {
    id: "video-004",
    type: "video",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    caption: "Danzas tradicionales — Paso de la Patria 2024",
    alt: "Video de danzas tradicionales",
    year: 2024,
  },
];
